### ISSUE TITLE
Python2 wheels contain incorrect dependency information

### ISSUE THREAD

**Issue by greschd** [PyCQA/prospector#274] opened 2018-08-09 10:46 UTC
Using python2, ``pip install prospector`` fails with 

```
Collecting prospector
  Using cached https://files.pythonhosted.org/packages/8a/94/d1643eb5460f3accc4609e2fe14ffe9e6dab2b1014b047fccab68b3ee5cb/prospector-1.1.1-py2.py3-none-any.whl
Collecting pylint>=2 (from prospector)
  Could not find a version that satisfies the requirement pylint>=2 (from prospector) (from versions: 0.15.2, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.27.0, 0.28.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0, 1.9.1, 1.9.2, 1.9.3)
No matching distribution found for pylint>=2 (from prospector)
```

while ``pip install prospector --no-binary prospector`` works as expected. This is probably due to incorrect dependency information in the universal wheel uploaded on PyPI.

**Comment by carlio** [comment] 2018-10-05 17:19
This should be fixed due to https://github.com/PyCQA/prospector/blob/master/setup.py#L33 - are you still having this issue?

**Comment by gopackgo90** [comment] 2018-10-05 19:39
Doesn't appear so:
```
(test_prospector) [me@pc ~]$ pip install prospector
Collecting prospector
  Downloading https://files.pythonhosted.org/packages/6d/2c/fd155836d2973a35ac0acd9c64e44fc5a7034cbf8ff4c7e3f0c0e61d1381/prospector-1.1.3-py2.py3-none-any.whl (65kB)
    100% |████████████████████████████████| 71kB 6.2MB/s 
Collecting pyyaml (from prospector)
Collecting pylint-plugin-utils>=0.2.6 (from prospector)
  Downloading https://files.pythonhosted.org/packages/b1/c1/75a481b103fecf8065300681c460dbed80105098c5d63f995ab0949fbfac/pylint-plugin-utils-0.4.tar.gz
Collecting dodgy>=0.1.9 (from prospector)
Collecting pydocstyle>=2.0.0 (from prospector)
  Using cached https://files.pythonhosted.org/packages/4e/20/c710bd30d53c2786d1d9980a5f66598fb3e7348699858f40def7d625dedb/pydocstyle-2.1.1-py2-none-any.whl
Collecting pylint>=2 (from prospector)
  Could not find a version that satisfies the requirement pylint>=2 (from prospector) (from versions: 0.15.2, 0.16.0, 0.18.0, 0.18.1, 0.19.0, 0.20.0, 0.21.0, 0.21.1, 0.21.2, 0.21.3, 0.22.0, 0.23.0, 0.24.0, 0.25.0, 0.25.1, 0.25.2, 0.26.0, 0.27.0, 0.28.0, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.9.0, 1.9.1, 1.9.2, 1.9.3)
No matching distribution found for pylint>=2 (from prospector)
```

**Comment by carlio** [comment] 2018-10-05 19:50
Strange I can't think why that might be the case, it's sort of saying 'pylint>=2' but then listing possibilities that are '<2'. Could you dump your `pip freeze` and `pip --version` and `python --version`?

Also, check out https://github.com/landscapeio/prospector2 which I created as a fork because prospector, pylint and most dependencies are moving away from python 2.

**Comment by gopackgo90** [comment] 2018-10-05 19:57
I agree it is very weird.
```
(test_prospector) [me@pc ~]$ pip freeze
(test_prospector) [me@pc ~]$ pip --version
pip 18.1 from /home/me/python_envs/test_prospector/lib/python2.7/site-packages/pip (python 2.7)
(test_prospector) [me@pc ~]$ python --version
Python 2.7.5
```

**Comment by gopackgo90** [comment] 2018-10-05 20:08
This is interesting. If I downgrade pip to 8.1.2, then prospector installs fine.
```
(test_prospector) [me@pc ~]$ pip install pip==8.1.2
...
(test_prospector) [me@pc ~]$ pip install prospector
...
Successfully installed astroid-2.0.4 configparser-3.5.0 dodgy-0.1.9 enum34-1.1.6 flake8-3.5.0 flake8-polyfill-1.0.2 futures-3.2.0 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 pep8-naming-0.7.0 prospector-1.1.3 pycodestyle-2.3.1 pydocstyle-2.1.1 pyflakes-1.6.0 pylint-2.1.1 pylint-plugin-utils-0.4 pyyaml-3.13 requirements-detector-0.6 setoptconf-0.2.0 six-1.11.0 snowballstemmer-1.2.1 typing-3.6.6 wrapt-1.10.11
(test_prospector) [me@pc ~]$ pip freeze
astroid==2.0.4
configparser==3.5.0
dodgy==0.1.9
enum34==1.1.6
flake8==3.5.0
flake8-polyfill==1.0.2
futures==3.2.0
isort==4.3.4
lazy-object-proxy==1.3.1
mccabe==0.6.1
pep8-naming==0.7.0
prospector==1.1.3
pycodestyle==2.3.1
pydocstyle==2.1.1
pyflakes==1.6.0
pylint==2.1.1
pylint-plugin-utils==0.4
PyYAML==3.13
requirements-detector==0.6
setoptconf==0.2.0
six==1.11.0
snowballstemmer==1.2.1
typing==3.6.6
wrapt==1.10.11
```

**Comment by greschd** [comment] 2018-10-05 22:15
I think the versions listed are simply the ones which advertise compatibility with Python 2, and are thus "installable". Probably this check is only done in newer versions of pip. In your last example it ends up installing ``pylint==2.1.1``, which in principle shouldn't be compatible with Python2.

**Comment by carlio** [comment] 2018-10-06 04:43
Seems like the problem is that building the wheel is done with python3 which sets the pylint version in metadata. I never built wheels so I have no idea. @chocoelho do you build wheels when you upload new versions? Or is this a new PyPI feature? 🤷‍♂️   Either way the wheel no longer uses the `setup.py` so that initial fix won't work. 

Since a wheel is supposed to be 'universal' and that is no longer true for prospector due to dependencies being py3 only after a certain point, I think just no longer making wheels is the way to fix this...

**Comment by carlio** [comment] 2018-10-06 04:48
@greschd @gopackgo90 I just deleted the wheel from the 1.1.3 release, and I am curious if that will now work to install for you as it'd only use the sdist tarball now?

**Comment by carlio** [comment] 2018-10-07 08:33
So @chocoelho looks like we should abandon wheels for now until we figure out the right way to distribute this, though doing #265 might solve that issue.

**Comment by chocoelho** [comment] 2018-10-07 15:57
@carlio I usually build using wheel with `--universal`. If we are to maintain Python 2 support here, wheels shouldn't be sent to Pypi.

**Comment by carlio** [comment] 2018-10-07 17:00
@chocoelho Then lets stop using wheels (or at least, stop putting them on PyPi) for now until we figure this out as it seems to break things a bit.

**Comment by carlio** [comment] 2018-10-07 17:02
I will close this for now as it seems the problem is in the packaging so using tarball releases only will fix this; a better solution should come along but at least the reason for this issue report is found and fixed.

**Closed by carlio** 2018-10-07 17:02 UTC
