### ISSUE TITLE
[BUG] bandit check is not working?

### ISSUE THREAD

**Issue by dmashine** [PyCQA/prospector#364] opened 2019-12-16 08:57 UTC
**Describe the bug**
I guess, bandit check is not working.

**To Reproduce**
1. Install prospector[with_bandit], install bandit
2. add a line like `SECRET_KEY = "awdawdawdawd"` (default in Django settings.py)
3. Check with `prospector mymodule --uses django -w bandit`. No errors for any strictness lvl.
4. If i check with `bandit -r mysite` it reports "possible hardcoded password string"

**Expected behavior**
`prospector -w bandit` should find the hardcoded string

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.3
 - Tool bandit
 - Prospector version 1.2.0
- Python version 3.6.9

**Comment by carlio** [comment] 2022-02-28 08:08
I will close this because it's quite old and uses old versions of prospector, but also because when installing using python 3.6 and prospector 1.2.0 I was not able to reproduce this problem:

```
$ prospector -t bandit --uses django --messages-only
Messages
========

testproj/settings.py
  Line: 23
    bandit: B105 / Possible hardcoded password: 'oihjaerg'
```

**Closed by carlio** 2022-02-28 08:08 UTC
Labels: investigate
