### ISSUE TITLE
PylintTool mangles absolute paths on single file check, causes check to fail

### ISSUE THREAD

**Issue by tmcdonnell87** [PyCQA/prospector#214] opened 2017-05-05 22:12 UTC
Tested with Prospector 0.12.5 on Windows Subsystem for Linux. 

*Expected*
Running Pylint via prospector on an absolute path `/mnt/c/path/file.py` runs all checks as expected.
*Actual*
Check crashes due to not being able to find spurious path. 

*Details*
Assume run from `/mnt/c/path` on `/mnt/c/path/file.py`.
https://github.com/landscapeio/prospector/blob/master/prospector/tools/pylint/__init__.py#L114 splits the path into `[['', 'mnt', 'c', 'path', 'file.py']]`
https://github.com/landscapeio/prospector/blob/master/prospector/tools/pylint/__init__.py#L118 puts it back together as `mnt/c/path/file.py`. This then gets re-absoluted as `/mnt/c/path/mnt/c/path/file.py`. This does not exist, so the check fails.

**Comment by RoscoP** [comment] 2018-01-09 19:59
I have the same issue on Windows.

- md c:\fullpathto
- cd c:\fullpathto
- virtualenv venv
- venv\scripts\activate.ps1
- pip install prospector
- echo 'print("hello")' | set-content test.py #using powershell
- prospector --no-autodetect c:\fullpathto\test.py
```
(venv) C:\fullpathto> prospector.exe --no-autodetect test.py
Check Information
=================
         Started: 2018-01-09 11:54:55.132000
        Finished: 2018-01-09 11:54:55.475000
      Time Taken: 0.34 seconds
       Formatter: grouped
        Profiles: default, no_doc_warnings, no_test_warnings, strictness_medium, strictness_high, strictness_veryhigh, no_member_warnings
      Strictness: None
  Libraries Used:
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 0

(venv) C:\fullpathto> prospector.exe --no-autodetect c:\fullpathto\test.py
Messages
========

fullpathto\test.py
  Line: 1
    pylint: fatal / No module named c:\fullpathto\fullpathto\test.py



Check Information
=================
         Started: 2018-01-09 11:55:06.899000
        Finished: 2018-01-09 11:55:07.247000
      Time Taken: 0.35 seconds
       Formatter: grouped
        Profiles: default, no_doc_warnings, no_test_warnings, strictness_medium, strictness_high, strictness_veryhigh, no_member_warnings
      Strictness: None
  Libraries Used:
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 1
```

**Comment by carlio** [comment] 2022-02-26 05:15
I'm going to close this because it's super old now and I just tried to reproduce locally and did not get the same crash.

I suspect it was fixed either on purpose or as a side effect of another change in the time since this bug was reported.

If you still find it happens for you with newer versions of prospector please let me know - it's on v1.7.1 now so definitely quite a lot has changed ins v0.12.7 !

**Closed by carlio** 2022-02-26 05:15 UTC
