### ISSUE TITLE
Diffrent behavoiur with different abs/relative arguments

### ISSUE THREAD

**Issue by meteozond** [PyCQA/prospector#257] opened 2018-06-09 07:50 UTC
It is quite disappointing when overall project, separate file and folder checks give different results. Here is a little table showing results depended on arguments given.

<table border=1>
  <thead>
<tr>
 <td rowspan=3><b>cmd</td>
 <td rowspan=3><b>--absolute-path</td>
 <td colspan=7><b>PATH</td>
 <td colspan=3 rowspan="2"><b>results</td>
</tr>
<tr>
 <td rowspan=2><b>not defined</td>
 <td rowspan=2><b>Full path to project</td>
 <td rowspan=2><b>.</td>
 <td colspan=2><b>file</td>
 <td colspan=2><b>folder</td>
</tr>
<tr>
 <td><b>relative</td>
 <td><b>abs</td>
 <td><b>relative</td>
 <td><b>abs</td>
 <td><b>code</td>
 <td><b>import-error</td>
 <td><b>ignored noqa</td>
</tr>
  </thead>
  
<tr><td>  </td>
  <td>-</td><td>*</td><td> </td><td> </td><td> </td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>
  
<tr><td>   `pwd`</td>
  <td>-</td><td> </td><td>*</td><td> </td><td> </td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>

<tr><td>   .</td>
  <td>-</td><td> </td><td> </td><td>*</td><td> </td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>

<tr><td>   lib/__init__.py</td>
  <td>-</td><td> </td><td> </td><td> </td><td>*</td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>

<tr><td>   `pwd`/lib/__init__.py</td>
  <td>-</td><td> </td><td> </td><td> </td><td> </td><td>*</td><td> </td><td> </td><td>fail</td><td> </td><td>*</td></tr>

<tr><td>   lib</td>
  <td>-</td><td> </td><td> </td><td> </td><td> </td><td> </td><td>*</td><td> </td><td>fail</td><td>*</td><td>*</td></tr>

<tr><td>   `pwd`/lib</td>
  <td>-</td><td> </td><td> </td><td> </td><td> </td><td> </td><td> </td><td>*</td><td>fail</td><td>*</td><td>*</td></tr>

<tr><td>   --absolute-path</td>
  <td>+</td><td>*</td><td> </td><td> </td><td> </td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>

<tr><td>   --absolute-path `pwd`</td>
  <td>+</td><td> </td><td>*</td><td> </td><td> </td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>

<tr><td>   --absolute-path .</td>
  <td>+</td><td> </td><td> </td><td>*</td><td> </td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>

<tr><td>   --absolute-path lib/__init__.py</td>
  <td>+</td><td> </td><td> </td><td> </td><td>*</td><td> </td><td> </td><td> </td><td>ok  </td><td> </td><td> </td></tr>

<tr><td>   --absolute-path `pwd`/lib/__init__.py</td>
  <td>+</td><td> </td><td> </td><td> </td><td> </td><td>*</td><td> </td><td> </td><td>ok</td><td> </td><td> </td></tr>

<tr><td>   --absolute-path lib</td>
  <td>+</td><td> </td><td> </td><td> </td><td> </td><td> </td><td>*</td><td> </td><td>fail</td><td>*</td><td>*</td></tr>

<tr><td>   --absolute-path `pwd`/lib</td>
  <td>+</td><td> </td><td> </td><td> </td><td> </td><td> </td><td> </td><td>*</td><td>fail</td><td>*</td><td>*</td></tr>

</table>

**Comment by chocoelho** [comment] 2018-06-14 17:33
Hey there, sorry for the delay. I've been quite busy these days due to some personal things but I'm getting back to maintenance here. I'll investigate that this week, prioritizing bugfixes before anything else, but I just want to confirm that this issue is happening using the latest version of prospector. Can you confirm me that?

**Comment by meteozond** [comment] 2018-06-15 06:54
Hi @chocoelho! Thanks for you interest. I've decided to check this case right after 0.12.11 release fixed my previous report #244. Latest update fixed some issues, but unfortunately still affected.

```bash
$ pip freeze | grep prospector

prospector==0.12.11
```

```bash
$ prospector --absolute-path `pwd`/lib

Messages
========

...

Check Information
=================
         Started: 2018-06-15 09:41:39.833960
        Finished: 2018-06-15 09:41:46.639318
      Time Taken: 6.81 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, strictness_veryhigh, no_doc_warnings, no_member_warnings
      Strictness: from profile
  Libraries Used: 
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 21

```

```
$ prospector --absolute-path

Check Information
=================
         Started: 2018-06-15 09:51:53.621297
        Finished: 2018-06-15 09:52:40.168239
      Time Taken: 46.55 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, strictness_veryhigh, no_doc_warnings, no_member_warnings
      Strictness: from profile
  Libraries Used: 
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 0

```

**Comment by pawamoy** [comment] 2018-06-15 07:03
Maybe try deactivating plugins and see if one of them is responsible? I would suggest to start with pylint.

**Comment by meteozond** [comment] 2018-06-15 07:17
@pawamoy, `import-error` messages are definitely `pylint` related (at least all of them are pylint reports), but as I see the problem is in `prospector` provided `pylint` configuration. Ignored `noqa` problem is post processing filtering related and it is most likely `prospector` `core` problem.

**Comment by chocoelho** [comment] 2018-06-15 14:14
The issue is definitely within `prospector`. I'm taking a look at it right now to find the source of the issue and release a patch ASAP.

**Comment by chocoelho** [comment] 2018-06-30 14:49
Just an update: seems like some tools are only running in certain conditions thus the difference of results, and looks like one of these tools is `pep8`. I'm still investigating the source of the issue with whatever little free time I've got.

**Comment by chocoelho** [comment] 2018-07-06 14:40
Another update: I've managed to deal with `pep8` not being properly applied, but there's also the issue with `pylint` return false positives of `import-self` errors. Again, sorry for taking too long to resolve this issue, but some personal matters are taking too much time from me.

**Comment by meteozond** [comment] 2018-08-01 09:18
@chocoelho We've checked out new version and looks like most issues gone. But I've found that running check on folder witch submodule depends on parent folder still gives import errors.

```
- a/
  - __init__.py
  - b.py
      import c
- c.py
```

- checking `a` gives import-error
- checking `b` doesn't

I'm not sure but it looks like issue is working dir detection dependent when folder check issued.

**Comment by Deimos** [comment] 2018-08-30 07:38
This issue doesn't seem to be completely resolved. Running a bare `prospector` from my project's root directory gives no errors found, but if I pass it the name of the subdirectory that includes all the app code, it finds and reports multiple pep8 errors. So it appears that pep8 isn't actually checking that directory normally.

(username mentions in case they won't see this comment on a closed issue otherwise - @chocoelho @carlio)

**Comment by chocoelho** [comment] 2018-08-30 13:20
Due to multiple requests, I'm reopening this issue. Will check that today or tomorrow :slightly_smiling_face:

**Comment by Deimos** [comment] 2018-08-30 18:02
Thanks. My project is open-source if you want to look at the structure or even clone it and try running against it directly. [It's here on GitLab](https://gitlab.com/tildes/tildes) and there's a [mirror on GitHub too](https://github.com/spectria/tildes) if that's easier. Specifically, running `prospector` in the root doesn't report issues, but if I run `prospector tildes` it will report a few pep8 errors from files in the `tildes/lib/` directory.

**Comment by chocoelho** [comment] 2018-10-05 17:10
@meteozond Sorry for the delay, it's been crazy over here with the coming of my son, so my time has been limited for a while. Checking here, it seems to be related to how we get the minimal path from the found files. In your example, it's taking `a` into consideration and not the root, although `a` is not the root. Checking here how to properly fix this minimal path discovery.

**Comment by chocoelho** [comment] 2018-10-05 17:12
@Deimos I'm checking here as well, your issue seems more related to how `pep8` discovery works, a little bit different from the issue reported but I'm looking into it as I have the time to do so. Sorry for not being able to be more helpful.

**Comment by Deimos** [comment] 2018-10-05 19:16
It's no problem at all, don't worry about the delay. I appreciate you looking into it whenever you get a chance, thanks.

**Comment by meteozond** [comment] 2018-11-20 18:31
@chocoelho all of issues from my first message gone, but I've got new one :(

False `relative-beyond-top-level` `pylint` detection, for project subfolder check.
I'm going to make proper checks to start new issue later.

**Comment by Deimos** [comment] 2018-11-20 20:46
@chocoelho Behavior doesn't seem to change for me. For both 1.1.3 and 1.1.5, `prospector` in the root directory has zero messages, but `prospector tildes` has pep8 errors.

**Comment by chocoelho** [comment] 2018-11-22 14:37
Got it @meteozond @Deimos, will keep on check the reason of these issues

**Comment by chocoelho** [comment] 2018-12-14 16:59
@Deimos can you check again?

**Comment by Deimos** [comment] 2018-12-14 20:55
Yes, the `develop` branch seems to work as expected now - bare `prospector` produces the pep8 errors now (same output as `prospector tildes`). So the issue with my project should be fixed, thanks!

**Comment by chocoelho** [comment] 2018-12-21 17:01
Closing this as it's reported as fixed :)

**Closed by chocoelho** 2018-12-21 17:01 UTC
