### ISSUE TITLE
[BUG] / Question: python prospector became very slow. ANy new slow dependencies?

### ISSUE THREAD

**Issue by feenes** [PyCQA/prospector#368] opened 2020-03-13 11:30 UTC
Prospector runs became very very slow.

Does anybody else notice, that prospector became slower in the last few days.
our CI runners do always freshly install prospector and do not version limit the dependencies.

I wanted to know first whether anybody else is encountering such issues?

I am still investigation, whether anything else changed in our CI infrastructure, but didn't find anything so far.

If nobody encounters anything like that within the next few days, then I assume it's not an issue with a prospector dependency and this should just be closed.

If however anybody encounter the same issues it would be interesting to indentify the dependency, that slows down

**Comment by chocoelho** [comment] 2020-03-14 20:42
@feenes What I notice that can get slower is whenever using pylint, specially when there's lot of files being linted. This can be fixed by running pylint with multiple jobs, but this can be only used together with prospector when pylint releases 2.5.0 which release date is still TBA. Try removing pylint from the run just to validate that this is the tool causing the issue, just to make sure in your case. Since we haven't had a release in a while, I'd say it's more something about the tools prospector is using, which pylint tends to be the most heavy one.

**Comment by feenes** [comment] 2020-03-17 11:06
Thanks for the info. 
I will check.

On my side I noticed, that this occurs just on a few gitlabci-runners and not on all.

Will check for any 'bugs' in these runners.

I think we can close this ticket.
Thanks for your answer.

**Comment by chocoelho** [comment] 2020-03-18 00:24
> Can I make sure, that prospector does not run multiple jobs for any task?
AFAICT, it doesn't. It's still in the very early stages for Pylint, and it requires 2.5.0 to be released.

**Comment by rik** [comment] 2020-05-21 18:17
Pylint 2.5 has now been released. I'm very interested in getting parallel job support (with or without [auto support](https://github.com/PyCQA/prospector/issues/320)). How can I help to upgrade the required version of pylint and release a new version of prospector?

**Comment by chocoelho** [comment] 2020-05-22 13:38
> How can I help to upgrade the required version of pylint and release a new version of prospector?

Sorry for not being very active these days, seems like WFH has been very demanding and now I'm working more than usual.

Prepare a PR with the update pointed to `develop` so I can review it over the weekend, as I'm going through some prospector issues and opened PRs by then. Once it gets approved and merged, I'll prepare a `dev` release so we can already test it. My plan is to release it into stable by the end of the month.

**Comment by chocoelho** [comment] 2020-05-25 03:45
@rik Hey there, just release 1.3.0.dev0. Can you check if this is still the case?

**Comment by rik** [comment] 2020-05-25 10:41
> Sorry for not being very active these days, seems like WFH has been very demanding and now I'm working more than usual.

Don't worry about that. I'm grateful for your contributions and you don't owe us anything. This period is even harder on us than usual. Take care of yourself!

> Hey there, just release 1.3.0.dev0. Can you check if this is still the case?

I gave it a try. The `jobs` option works!

Sadly, I get a lot of pylint messages about Django migrations. pylint-django [ignores migrations folders](https://github.com/PyCQA/pylint-django/blob/3afe91e200921d6440f4efc27a65ecf8bf617613/pylint_django/plugin.py#L22). I've confirmed this by running `pylint --jobs=4 --load-plugins pylint_django |grep migration` (The grep is to filter other issues that my prospector profile disables). I have an empty output when running pylint directly.

When I run through prospector though, it seems that the way we use the pylint API disables that setting from `pylint-django`.

**Comment by chocoelho** [comment] 2020-05-25 10:54
Awesome, that's what I wanted to catch with the dev releases. I should take a look at it later today. Thanks for the report.

**Comment by chocoelho** [comment] 2020-05-30 22:39
@rik I'm going to release another version, with some fixes for latest pylint usage. I've just uploaded version `1.3.0.dev3`.

**Comment by rik** [comment] 2020-05-30 23:37
I just gave it a try. Sadly, this does not improve the "ignore migration" issue.

**Comment by chocoelho** [comment] 2020-05-31 00:17
@rik In this case, I think it's better for us to move onto another issue so that you can provide more info to me. Share your environment, installed libraries, sandbox reproducible code if possible and so on.

**Comment by rik** [comment] 2020-06-01 13:47
Sure, I've opened https://github.com/PyCQA/prospector/issues/381 with a dedicated minimal repo to showcase the issue.

**Comment by chocoelho** [comment] 2020-06-01 22:53
As to the original, reported by @feenes: is that still the case with `1.3.0.dev3`?

**Comment by feenes** [comment] 2020-06-01 23:33
@chocoelho Tricky to know. I encountered this issue only sporadically on some gitlab runners.

When I counter the issue again I can try to see whether the runner is always provoking the issue and if it is I will update to 1.3.0.dev3 and see if the behaviour changes.

As you see: A lot of ifs. not sure, when I have the opportunity to give reliable feedback.

**Closed** 2020-06-20 17:09 UTC
Labels: investigate
