### ISSUE TITLE
option –pylint-config-file does not work 

### ISSUE THREAD

**Issue by 1oglop1** [PyCQA/prospector#226] opened 2017-07-29 16:58 UTC
Steps to reproduce:
1) run `prospector -DFM -s veryhigh –pylint-config-file pylintrc` 
or
1) run `prospector -DFM -s veryhigh –pylint-config-file "/full/path/pylintrc` 

Current behaviour:
 `In multi-path mode, all inputs must be files, not directories.`

Expected behaviuor: 
Use the `pylintrc` file.

**Comment by chocoelho** [comment] 2018-04-20 17:55
Is this still happening? I've tried to reproduce it, but it seems to be working properly.

**Comment by 1oglop1** [comment] 2018-04-20 19:11
Well the issue is pretty old, I haven't used prospector since, in favor of native tools.

**Comment by chocoelho** [comment] 2018-05-31 23:13
Closing this since we're unable to reproduce it for now.

**Closed by chocoelho** 2018-05-31 23:13 UTC
