### ISSUE TITLE
[BUG] requiring packaging = "<22.0" is not compatible with black >=23.1.0

### ISSUE THREAD

**Issue by ryancausey** [PyCQA/prospector#588] opened 2023-02-02 19:41 UTC
**Describe the bug** A clear and concise description of what the bug is.

The requirement of `packaging = "<22.0"` is incompatible with `black >=23.1.0`.

**To Reproduce** Steps to reproduce the behavior:

1. Run `poetry add --group dev black=23.1.0`
2. See error

**Expected behavior** A clear and concise description of what you expected to happen.

Prospector and Black should live happily alongside one another.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04.1 LTS
- Tool: black
- Prospector version: 1.8.4
- Python version: 3.9.6

**Additional context** Add any other context about the problem here. Putting the list of
dependencies installed, e.g. the output of `pip freeze` also helps.

```bash
Because black (23.1.0) depends on packaging (>=22.0)
 and prospector (1.8.4) depends on packaging (<22.0), black (23.1.0) is incompatible with prospector (1.8.4).
So, because test-package depends on both black (23.1.0) and prospector (1.8.4), version solving failed.
```

**Comment by Pierre-Sassoulas** [comment] 2023-02-02 20:15
Duplicate of #579, PR are welcome :)

**Closed by Pierre-Sassoulas** 2023-02-02 20:15 UTC
Labels: investigate
