### ISSUE TITLE
[BUG] Unclosed file warning for each file analyzed

### ISSUE THREAD

**Issue by ckleemann** [PyCQA/prospector#411] opened 2021-03-25 11:30 UTC
**Describe the bug**
Prospector creates a unclosed file warning for each file analyzed. The bug is due to an unclosed file handle in encoding.py: ```return tokenize.open(filepath).read()```. It was introduced in 83df4e33.

**To Reproduce**
1. export PYTHONWARNINGS=all
2. Call prospector 
3. See error

**Expected behavior**
The file handle should be closed for each file e.g. by using an context-manager.

**Screenshots**
```
unclosed file <_io.TextIOWrapper name='...' mode='r' encoding='utf-8'>
```

**Environment (please complete the following information):**
 - OS: Linux
 - Tool Prospector
 - Prospector version 1.3.1
 - Python version 3.7.3

**Additional context**
I will send an pull request for this issue shortly.

**Comment by carlio** [comment] 2022-02-26 05:40
Closing this issue because #412 was merged and released, and I was not able to reproduce locally with the latest version so it seems fixed.

**Closed by carlio** 2022-02-26 05:40 UTC
Labels: investigate
