### ISSUE TITLE
[BUG] Releases 1.8.1 and 1.8.2 on PyPI don't work when installed with_$EXTRA or with-$EXTRA

### ISSUE THREAD

**Issue by volans-** [PyCQA/prospector#545] opened 2022-12-01 14:00 UTC
**Describe the bug**

When trying to install the latest version of Prospector from PyPI `1.8.1` with some extras like `with_everything` or `with_pyroma` a warning is printed and Prospector is installed without the extras.

**To Reproduce**

```shell
$ pip install "prospector[with_pyroma]"
Collecting prospector[with_pyroma]
  Using cached prospector-1.8.1-py3-none-any.whl (85 kB)
WARNING: prospector 1.8.1 does not provide the extra 'with_pyroma'
...
```

or 

```shell
$ pip install "prospector[with_everything]"
Collecting prospector[with_everything]
  Using cached prospector-1.8.1-py3-none-any.whl (85 kB)
WARNING: prospector 1.8.1 does not provide the extra 'with_everything'
...
```

**Expected behavior**

It should install Prospector with the selected extras.

**Environment:**

- OS: macOS 12.6.1
- Prospector version 1.8.1
- Python versions: 3.9.15 and 3.10.8

**Comment by Pierre-Sassoulas** [comment] 2022-12-01 15:39
Does ``[with-everything]`` works ?

**Comment by volans-** [comment] 2022-12-01 15:41
> Isn't it related to this issue? [python-poetry/poetry#6819](https://github.com/python-poetry/poetry/issues/6819)

It looks like it, `[with-everything]` does actually work.

**Comment by Pierre-Sassoulas** [comment] 2022-12-01 15:46
I think we have to upgrade the doc, this is a poetry behavior that will be painful to change.

**Comment by ckleemann** [comment] 2022-12-01 16:40
This issue also happens when installing from pip. There is a glitch in the doc. Before it was [with **_** everything] now it is [with **-** everything]

**Comment by volans-** [comment] 2022-12-01 16:52
> It looks like it, `[with-everything]` does actually work.

Actually I have to correct myself, although the pip installation works, prospector is not able to run the extra tool though.

Repro steps:
```shell
$ pip install "prospector[with-everything]"
...

$ pip freeze | grep -E '(pyroma|prospector)'
prospector==1.8.1
pyroma==4.1

$ cat prospector.yaml
pyroma:
  run: true

$ prospector --profile prospector.yaml test/

Cannot run tool pyroma as support was not installed.
Please install by running 'pip install prospector[with_pyroma]'
```

**Comment by sbrunner** [comment] 2022-12-02 08:15
For me, you should publish prospector with on older version of poetry since it is fixed in pip...

**Comment by Pierre-Sassoulas** [comment] 2022-12-02 10:18
I think you mean we should use an old version of poetry when releasing but I did not understand "this is fixed in pip" @sbrunner ?

**Comment by sbrunner** [comment] 2022-12-02 10:41
In this issue https://github.com/python-poetry/poetry/issues/6819
It says that an issue in pip about [PEP 685](https://peps.python.org/pep-0685/#specification).
Issue in pip: https://github.com/pypa/pip/issues/11445
Merged pull request in packaging: https://github.com/pypa/packaging/pull/545
Release issue in packaging: https://github.com/pypa/packaging/issues/569
In the last message we see that should be done soon :-)

**Comment by Pierre-Sassoulas** [comment] 2022-12-02 11:13
Thanks for tracking the root cause 👍 So if I understand we should release using an old poetry and wait for the 22.2 release in pip and use the latest poetry only then ?

**Comment by volans-** [comment] 2022-12-07 09:54
@Pierre-Sassoulas I took the liberty to rename the task to be more clear. Do you happen to have an ETA for the resolution of this problem?
I was also wondering if there should be some other label applied to this task in addition to `Documentation`.

**Closed** 2022-12-08 09:58 UTC
Labels: documentation
